### ISSUE TITLE
Failed to load Camber.dll library

### ISSUE THREAD

**Issue by glavoc** [mzjensen/Camber#160]
using Civil3D 2022 13.4.214.0 and Dynamo 2.10.1.214, I'm missing most of the Camber nodes.

Dynamo.Exceptions.LibraryLoadFailedException: Failed to load library: C:\Users\USER\AppData\Roaming\Autodesk\C3D 2022\Dynamo\2.10\packages\Camber\bin\Camber.dll

Build error for library: C:\Users\USER\AppData\Roaming\Autodesk\C3D 2022\Dynamo\2.10\packages\Camber\bin\Camber.dll
Could not load type 'ExportableItem' from assembly 'AeccDataShortcutMgd, Version=13.4.214.0, Culture=neutral, PublicKeyToken=null'.

**Comment by mzjensen** [comment]
Please update to 2022.1 at a minimum per the compatibility table in the [release notes](https://github.com/mzjensen/Camber/releases/tag/v4.1.0).
