### ISSUE TITLE
Set Object Alignment Label Set (Feature Request)

### ISSUE THREAD

**Issue by KirkWM** [mzjensen/Camber#41]

**Comment by mzjensen** [comment]
Sorry Kirk, as much as I would love to do this, I don't expect to have time. Feel free to reopen this in the future if you want to tackle it.

**Comment by mzjensen** [comment]
There seems to be more interest in this, so I'm going to try and make it happen.

https://forum.dynamobim.com/t/camber-feedback-thread/68942/191?u=mzjensen
