### ISSUE TITLE
CodeSetStyle.CodeSetStyleItems not returning values for link and shape codes

### ISSUE THREAD

**Issue by mzjensen** [mzjensen/Camber#48]
https://forum.dynamobim.com/t/camber-feedback-thread/68942/68?u=mzjensen

**Comment by kelvinlj** [comment]
Hi Zachri,
Thanks for this addition with version 2.0, appreciate your efforts.

I just wanted to highlight another item that goes hand in hand with this one.

The function is pulling down the link and shape codes now, but doesn't have a way to differentiate between them, particularity if you're using AddPointItem or SetPayItems. 
Is there a way to specify Code Type?

**Comment by mzjensen** [comment]
Hey @kelvinlj,
Sorry for the delay. I'm not clear on the issue here. If I understand you correctly, then you should be able to filter the list of CodeSetStyleItems by using the CodeSetStyleItem.SubentityStyleType node. If that doesn't get you what you need, can you upload a screenshot to explain further?

**Comment by kelvinlj** [comment]
Hi Zachri,
As some background on this question, I've created a large list of code set styles in excel, and i want to import these into existing code set styles. I've made a few attempts but all haven't worked.
The biggest issue is adding the codes in the first place.
The node CodeSetStyle.AddPointItem will add Point codes, but i dont see how to add Link and Shape codes from excel.
Below is an image showing my attempt to filter sub-entity type to add a shape code item.
[https://1drv.ms/u/s!AgeAUPaXe78uieYpQAirjLlaMrN0RA?e=RmgCOP](url)

For some extra background, I've also attached a workspace which attempts to add Pay Items, Descriptions and Feature Line Styles to an existing code set style, unsuccessfully,
[https://1drv.ms/u/s!AgeAUPaXe78uieYqmc2KT9j-boMt2g?e=cSa5st](url)

**Comment by mzjensen** [comment]
OK I see, so the issue is not being able to add link and shape items. Yes, you are correct that this isn't possible at the moment. I was running into issues with those two early on and ended up leaving them out of the library until I could figure it out. I've opened a new issue since it's a little bit different than what this issue was focused on.

https://github.com/mzjensen/Camber/issues/108

**Comment by kelvinlj** [comment]
nice, i've updated those links aswell
