### ISSUE TITLE
Create Layer Merge Node

### ISSUE THREAD

**Issue by KirkWM** [mzjensen/Camber#60]
I hit an new challenge when importing line work from pdfs and the pdf layer was the same but autocad put a prefix before for each pdf so no I have 30 sets of duplicate layers I want to merge

**Comment by mzjensen** [comment]
Thanks for posting, Kirk! This is an interesting one. It seems like this could be done pretty easily by selecting all of the layers in the Layer Manager and merging them all to whatever target layer you need.

But, just because there might be a simple UI solution doesn't mean that having a node for it wouldn't be valuable in other cases. Do you have any other ideas where this might come in handy?

**Comment by KirkWM** [comment]
All of these pdf pages have been inserted into a single dwg, then the line work is imported and layer names duplicated. I would have to click 30 times for all 20 layers = at least 600 clicks (plus scrolling).
![image](https://user-images.githubusercontent.com/75384301/146286587-45d74eaf-a028-49d4-8ff1-a9b0fb29b8ee.png)
 
![image](https://user-images.githubusercontent.com/75384301/146286706-1aa6776d-8874-43e4-a840-1d584d578e87.png)

**Comment by KirkWM** [comment]
another option is to type and filter layers using wild cards so there would be less clicks

**Comment by KirkWM** [comment]
layer translate tool can be of some service as well

**Comment by mzjensen** [comment]
Ah, I see! Yeah that's a pain. I can look at adding this. There isn't a method for it in the API so it will involve some gymnastics to find all of the objects on the layer, move them to the destination layer, then delete the old layer. Could get tricky for objects with blocks.

The easier way is probably to just send the LAYMRG command to the command line and supply the arguments.

**Comment by mzjensen** [comment]
Sorry Kirk, I'm going to close this for now. I'm trying to whittle down the to-do list and focus on the items that have frequently been requested.
