### ISSUE TITLE
TIN Surfaces to Dynamo surfaces

### ISSUE THREAD

**Issue by juanmciller** [mzjensen/Camber#64]
Hi mzjensen. 

I was encouraged to post here a possible enhancement in Camber package and it´d be to have the possibility to transform TIN Surfaces into Dynamo surfaces. As you know, currently we have to extract the triangles from the TIN Surface, patch them and merge all those surfaces. I do not know if it´d be possible to simplify that in one single node and also to reduce the time computing of Dynamo/machine. When we have, I am not going to say a medium-large surfaces, with just little surfaces, Dynamo usually gets stuck.

Thank you so much.

**Comment by mzjensen** [comment]
Thanks for posting! It's a great idea. I have thought about it too, and I know exactly what you mean. It can take a long time even with small surfaces. As the number of triangles increases (even just a little bit), the performance suffers dramatically.

I am assuming you know about the node from the Civil 3D Toolkit to get a TIN surface into Dynamo in Mesh format? It is super fast, but then I honestly don't really know what to do with meshes...

Do you typically want to have a PolySurface as the final product or the list of individual Surfaces for each triangle?

**Comment by juanmciller** [comment]
I have never tried to transform the TIN surface into a Mesh. Then, I guess you will have to transform that mesh into a Dynamo surface. Tomorrow I will look into it this workaround but I saw a toolkit for Meshes.

However, it is quite common to work with Dynamo for Civil 3D and TIN Surfaces and develop workflows with that kind of inputs. I guess it would be enough just having the whole surface merged. I mean, in stead of getting every single triangle as a surface, have all the surfaces of the triangles in a single Dynamo surface which is the same as the TIN surface. This workflow will open and allow us a huge amount of opportunities due to the fact that we would be able to access through the native Dynamo nodes which works with native surfaces.

**Comment by mzjensen** [comment]
I don't actually know how to convert a mesh to a surface, which is where I've always gotten stuck with the node from the Toolkit. It seems like it's only useful for visualizing the surface, but not actually doing anything with it. If you figure out how to convert, let me know!

But anyway, I fully agree with you. Making it easier to get the surface data would really help. Another thought I've had is that it would be nice to only grab a subset of the data. In my experience, you don't always need the entire TIN surface in Dynamo - you just need a specific area of interest, or perhaps a buffer around an object. What do you think about having the functionality to get TIN surface data into Dynamo, but only within a region of interest?

**Comment by juanmciller** [comment]
That sounds great! Having another input in the same node which can be a closed polycurve (boundary). If you plug it in, it will only import into Dynamo the triangles within the boundary. If anything is plugged,. Dynamo will import whole surface.

**Comment by mzjensen** [comment]
Hi @juanmciller,
I did some more testing with this, and unfortunately I don't think there is an efficient way to get TIN Surface geometry as a Dynamo Surface. A Dynamo Surface object (or a PolySurface) is just a very heavy object type to work with. No matter what approach you take, you still have to create individual Surfaces from the triangle geometry, either using _Surface.ByPatch_ with the triangle edges or _Surface.ByPerimeterPoints_ with the vertices of each triangle. So it doesn't really matter what I do behind the scenes, the limitation is still there.

I think the best solution is to provide the ability to only work with a subset of the triangles like we discussed earlier. It would look something like this. Would that work for you? The new node below would be the _TinSurface.GetTrianglesWithinBoundary_ node.

![image](https://user-images.githubusercontent.com/24361762/173998181-7b26aad5-dee2-4f45-a796-aaea8bcb889a.png)

**Comment by juanmciller** [comment]
Hi @mzjensen ,

yeh, I understand what you say above. It is a pity but at least your workaround makes the process easier and the computational time lower...

I like it. It´d be great to include it in Camber package. Should that polyline (boundary) be a Civil 3D boundary or you can just pick a polyline from the modelspace?

Thank-you!

**Comment by mzjensen** [comment]
You just pick a polyline in model space. Or there is another node where you can use a Dynamo polygon object for the boundary.

**Comment by mzjensen** [comment]
@juanmciller - these nodes are now available in v4.0.0.
