### ISSUE TITLE
Get Style by name and type

### ISSUE THREAD

**Issue by mzjensen** [mzjensen/Camber#7]
https://forum.dynamobim.com/t/camber-feedback-thread/68942/28?u=mzjensen

**Comment by kelvinlj** [comment]
Hi Zachri,
Im just making some plans for a codeset implementation and want to see if this item will allow for specifying Featurelinestyle, and CodeStyle by string when implemented?

**Comment by kelvinlj** [comment]
> 

Sounds good, i'm excited to have this capability. 
In terms of placement, no strong leaning, but if its just for Codesets, maybe Civil3D>Styles>CodeSetStyle or just within Styles for something more broad.

**Comment by mzjensen** [comment]
Not going to have time to implement this.
